name: Data Quality & Revenue Audit

on:
  push:
    branches: [ main ]
  schedule:
    # Runs at 00:00 every day (Bali Time is UTC+8)
    - cron: '16 0 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pandera duckdb

    - name: Run Audit Script
      run: python audit.py

    - name: Upload Error Reports
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: audit-failure-reports
        path: |
          stock_data_health_issues.csv
          sales_data_health_issues.csv